/* Auto-generated by scripts/process-photowall-stickers.mjs — do not edit by hand. */
import type { StickerCategory } from "./types";

function image(path: string): string {
  return `/stickers/${path}`;
}

export const AUTUMN_CATEGORIES: StickerCategory[] = [
  {
    id: "nature",
    name: "자연",
    stickers: [
      { id: "autumn.nature.maple", name: "단풍", kind: "image", src: image("autumn/nature/001-maple.png"), defaultWidth: 117, defaultHeight: 120 },
      { id: "autumn.nature.ginkgo", name: "은행잎", kind: "image", src: image("autumn/nature/002-ginkgo.png"), defaultWidth: 120, defaultHeight: 118 },
      { id: "autumn.nature.pumpkin", name: "호박", kind: "image", src: image("autumn/nature/003-pumpkin.png"), defaultWidth: 114, defaultHeight: 120 },
      { id: "autumn.nature.acorn", name: "도토리", kind: "image", src: image("autumn/nature/004-acorn.png"), defaultWidth: 89, defaultHeight: 120 },
      { id: "autumn.nature.mushroom", name: "버섯", kind: "image", src: image("autumn/nature/005-mushroom.png"), defaultWidth: 99, defaultHeight: 120 },
      { id: "autumn.nature.leaves", name: "낙엽", kind: "image", src: image("autumn/nature/006-leaves.png"), defaultWidth: 87, defaultHeight: 120 },
    ],
  },
  {
    id: "cozy",
    name: "포근",
    stickers: [
      { id: "autumn.cozy.cocoa", name: "핫초코", kind: "image", src: image("autumn/cozy/007-cocoa.png"), defaultWidth: 108, defaultHeight: 120 },
      { id: "autumn.cozy.scarf", name: "목도리", kind: "image", src: image("autumn/cozy/008-scarf.png"), defaultWidth: 120, defaultHeight: 114 },
      { id: "autumn.cozy.sweater", name: "니트", kind: "image", src: image("autumn/cozy/009-sweater.png"), defaultWidth: 120, defaultHeight: 120 },
      { id: "autumn.cozy.persimmon", name: "감", kind: "image", src: image("autumn/cozy/010-persimmon.png"), defaultWidth: 120, defaultHeight: 116 },
      { id: "autumn.cozy.wreath", name: "리스", kind: "image", src: image("autumn/cozy/011-wreath.png"), defaultWidth: 120, defaultHeight: 117 },
      { id: "autumn.cozy.campfire", name: "캠프파이어", kind: "image", src: image("autumn/cozy/012-campfire.png"), defaultWidth: 120, defaultHeight: 109 },
    ],
  },
];

// 12 stickers
