/* Auto-generated by scripts/process-photowall-stickers.mjs — do not edit by hand. */
import type { StickerCategory } from "./types";

function image(path: string): string {
  return `/stickers/${path}`;
}

export const BASIC_CATEGORIES: StickerCategory[] = [
  {
    id: "deco",
    name: "꾸미기",
    stickers: [
      { id: "basic.heart", name: "하트", kind: "image", src: image("basic/deco/001-heart.png"), defaultWidth: 120, defaultHeight: 111 },
      { id: "basic.star", name: "별", kind: "image", src: image("basic/deco/002-star.png"), defaultWidth: 120, defaultHeight: 118 },
      { id: "basic.sparkle", name: "반짝", kind: "image", src: image("basic/deco/003-sparkle.png"), defaultWidth: 112, defaultHeight: 120 },
      { id: "basic.camera", name: "카메라", kind: "image", src: image("basic/deco/004-camera.png"), defaultWidth: 120, defaultHeight: 112 },
      { id: "basic.bow", name: "리본", kind: "image", src: image("basic/deco/005-bow.png"), defaultWidth: 120, defaultHeight: 115 },
      { id: "basic.flower", name: "꽃", kind: "image", src: image("basic/deco/006-flower.png"), defaultWidth: 120, defaultHeight: 116 },
      { id: "basic.pin", name: "핀", kind: "image", src: image("basic/deco/007-pin.png"), defaultWidth: 79, defaultHeight: 120 },
      { id: "basic.tape", name: "테이프", kind: "image", src: image("basic/deco/008-tape.png"), defaultWidth: 120, defaultHeight: 48 },
    ],
  },
  {
    id: "cute",
    name: "귀여움",
    stickers: [
      { id: "basic.polaroid", name: "폴라로이드", kind: "image", src: image("basic/cute/009-polaroid.png"), defaultWidth: 105, defaultHeight: 120 },
      { id: "basic.moon", name: "달", kind: "image", src: image("basic/cute/010-moon.png"), defaultWidth: 114, defaultHeight: 120 },
      { id: "basic.cloud", name: "구름", kind: "image", src: image("basic/cute/011-cloud.png"), defaultWidth: 120, defaultHeight: 77 },
      { id: "basic.smile", name: "스마일", kind: "image", src: image("basic/cute/012-smile.png"), defaultWidth: 119, defaultHeight: 120 },
    ],
  },
];

// 12 stickers
