/* Auto-generated by scripts/process-photowall-stickers.mjs — do not edit by hand. */
import type { StickerCategory } from "./types";

function image(path: string): string {
  return `/stickers/${path}`;
}

export const CAFE_CATEGORIES: StickerCategory[] = [
  {
    id: "drink",
    name: "음료",
    stickers: [
      { id: "cafe.drink.latte", name: "라떼", kind: "image", src: image("cafe/drink/001-latte.png"), defaultWidth: 120, defaultHeight: 111 },
      { id: "cafe.drink.espresso", name: "에스프레소", kind: "image", src: image("cafe/drink/002-espresso.png"), defaultWidth: 120, defaultHeight: 116 },
      { id: "cafe.drink.teapot", name: "티팟", kind: "image", src: image("cafe/drink/003-teapot.png"), defaultWidth: 120, defaultHeight: 96 },
      { id: "cafe.drink.matcha", name: "말차", kind: "image", src: image("cafe/drink/004-matcha.png"), defaultWidth: 95, defaultHeight: 120 },
    ],
  },
  {
    id: "bite",
    name: "디저트",
    stickers: [
      { id: "cafe.bite.croissant", name: "크루아상", kind: "image", src: image("cafe/bite/005-croissant.png"), defaultWidth: 120, defaultHeight: 102 },
      { id: "cafe.bite.macaron", name: "마카롱", kind: "image", src: image("cafe/bite/006-macaron.png"), defaultWidth: 81, defaultHeight: 120 },
      { id: "cafe.bite.cookie", name: "쿠키", kind: "image", src: image("cafe/bite/007-cookie.png"), defaultWidth: 120, defaultHeight: 108 },
      { id: "cafe.bite.toast", name: "토스트", kind: "image", src: image("cafe/bite/008-toast.png"), defaultWidth: 120, defaultHeight: 108 },
      { id: "cafe.bite.book", name: "책", kind: "image", src: image("cafe/bite/009-book.png"), defaultWidth: 120, defaultHeight: 89 },
      { id: "cafe.bite.candle", name: "캔들", kind: "image", src: image("cafe/bite/010-candle.png"), defaultWidth: 97, defaultHeight: 120 },
      { id: "cafe.bite.plant", name: "화분", kind: "image", src: image("cafe/bite/011-plant.png"), defaultWidth: 86, defaultHeight: 120 },
      { id: "cafe.bite.record", name: "레코드", kind: "image", src: image("cafe/bite/012-record.png"), defaultWidth: 120, defaultHeight: 95 },
    ],
  },
];

// 12 stickers
