/* Auto-generated by scripts/process-photowall-stickers.mjs — do not edit by hand. */
import type { StickerCategory } from "./types";

function image(path: string): string {
  return `/stickers/${path}`;
}

export const CUTE_CATEGORIES: StickerCategory[] = [
  {
    id: "animals",
    name: "동물",
    stickers: [
      { id: "cute.animals.puppy", name: "강아지", kind: "image", src: image("cute/animals/001-puppy.png"), defaultWidth: 115, defaultHeight: 120 },
      { id: "cute.animals.kitten", name: "고양이", kind: "image", src: image("cute/animals/002-kitten.png"), defaultWidth: 109, defaultHeight: 120 },
      { id: "cute.animals.bear", name: "곰돌이", kind: "image", src: image("cute/animals/003-bear.png"), defaultWidth: 104, defaultHeight: 120 },
      { id: "cute.animals.bunny", name: "토끼", kind: "image", src: image("cute/animals/004-bunny.png"), defaultWidth: 96, defaultHeight: 120 },
      { id: "cute.animals.chick", name: "병아리", kind: "image", src: image("cute/animals/005-chick.png"), defaultWidth: 113, defaultHeight: 120 },
      { id: "cute.animals.hamster", name: "햄스터", kind: "image", src: image("cute/animals/006-hamster.png"), defaultWidth: 109, defaultHeight: 120 },
    ],
  },
  {
    id: "sweets",
    name: "간식",
    stickers: [
      { id: "cute.sweets.pudding", name: "푸딩", kind: "image", src: image("cute/sweets/007-pudding.png"), defaultWidth: 111, defaultHeight: 120 },
      { id: "cute.sweets.candy", name: "캔디", kind: "image", src: image("cute/sweets/008-candy.png"), defaultWidth: 120, defaultHeight: 76 },
      { id: "cute.sweets.milk", name: "우유", kind: "image", src: image("cute/sweets/009-milk.png"), defaultWidth: 99, defaultHeight: 120 },
      { id: "cute.sweets.peach", name: "복숭아", kind: "image", src: image("cute/sweets/010-peach.png"), defaultWidth: 112, defaultHeight: 120 },
      { id: "cute.sweets.donut", name: "도넛", kind: "image", src: image("cute/sweets/011-donut.png"), defaultWidth: 120, defaultHeight: 112 },
      { id: "cute.sweets.paw", name: "발바닥", kind: "image", src: image("cute/sweets/012-paw.png"), defaultWidth: 120, defaultHeight: 119 },
    ],
  },
];

// 12 stickers
