/* Auto-generated by scripts/process-photowall-stickers.mjs — do not edit by hand. */
import type { StickerCategory } from "./types";

function image(path: string): string {
  return `/stickers/${path}`;
}

export const DAKU_CATEGORIES: StickerCategory[] = [
  {
    id: "chars",
    name: "캐릭터",
    stickers: [
      { id: "daku.chars.heart-bear", name: "하트곰", kind: "image", src: image("daku/chars/001-heart-bear.png"), defaultWidth: 100, defaultHeight: 120 },
      { id: "daku.chars.heart-puppy", name: "하트멍", kind: "image", src: image("daku/chars/002-heart-puppy.png"), defaultWidth: 120, defaultHeight: 108 },
      { id: "daku.chars.sleepy-cat", name: "잠냥이", kind: "image", src: image("daku/chars/003-sleepy-cat.png"), defaultWidth: 120, defaultHeight: 93 },
      { id: "daku.chars.duck", name: "오리", kind: "image", src: image("daku/chars/004-duck.png"), defaultWidth: 87, defaultHeight: 120 },
      { id: "daku.chars.frog", name: "개구리", kind: "image", src: image("daku/chars/005-frog.png"), defaultWidth: 118, defaultHeight: 120 },
      { id: "daku.chars.chick-bow", name: "리본병아리", kind: "image", src: image("daku/chars/006-chick-bow.png"), defaultWidth: 107, defaultHeight: 120 },
      { id: "daku.chars.panda", name: "팬더", kind: "image", src: image("daku/chars/007-panda.png"), defaultWidth: 120, defaultHeight: 104 },
      { id: "daku.chars.bunny-heart", name: "하트토끼", kind: "image", src: image("daku/chars/008-bunny-heart.png"), defaultWidth: 78, defaultHeight: 120 },
    ],
  },
  {
    id: "accents",
    name: "데코",
    stickers: [
      { id: "daku.accents.cherries", name: "체리", kind: "image", src: image("daku/accents/009-cherries.png"), defaultWidth: 113, defaultHeight: 120 },
      { id: "daku.accents.big-bow", name: "왕리본", kind: "image", src: image("daku/accents/010-big-bow.png"), defaultWidth: 120, defaultHeight: 114 },
      { id: "daku.accents.daisy", name: "데이지", kind: "image", src: image("daku/accents/011-daisy.png"), defaultWidth: 120, defaultHeight: 116 },
      { id: "daku.accents.washi-tape", name: "마스킹", kind: "image", src: image("daku/accents/012-washi-tape.png"), defaultWidth: 120, defaultHeight: 58 },
      { id: "daku.accents.speech-heart", name: "말풍선", kind: "image", src: image("daku/accents/013-speech-heart.png"), defaultWidth: 120, defaultHeight: 113 },
      { id: "daku.accents.cupcake", name: "컵케이크", kind: "image", src: image("daku/accents/014-cupcake.png"), defaultWidth: 88, defaultHeight: 120 },
      { id: "daku.accents.star-badge", name: "별뱃지", kind: "image", src: image("daku/accents/015-star-badge.png"), defaultWidth: 120, defaultHeight: 114 },
      { id: "daku.accents.mini-flower", name: "미니꽃", kind: "image", src: image("daku/accents/016-mini-flower.png"), defaultWidth: 120, defaultHeight: 113 },
    ],
  },
];

// 16 stickers
