/* Auto-generated by scripts/process-photowall-stickers.mjs — do not edit by hand. */
import type { StickerCategory } from "./types";

function image(path: string): string {
  return `/stickers/${path}`;
}

export const LOVE_CATEGORIES: StickerCategory[] = [
  {
    id: "hearts",
    name: "하트",
    stickers: [
      { id: "love.hearts.double-heart", name: "더블하트", kind: "image", src: image("love/hearts/001-double-heart.png"), defaultWidth: 120, defaultHeight: 83 },
      { id: "love.hearts.arrow-heart", name: "큐피드", kind: "image", src: image("love/hearts/002-arrow-heart.png"), defaultWidth: 120, defaultHeight: 92 },
      { id: "love.hearts.love-letter", name: "러브레터", kind: "image", src: image("love/hearts/003-love-letter.png"), defaultWidth: 120, defaultHeight: 93 },
      { id: "love.hearts.rose", name: "장미", kind: "image", src: image("love/hearts/004-rose.png"), defaultWidth: 112, defaultHeight: 120 },
      { id: "love.hearts.kiss-mark", name: "키스마크", kind: "image", src: image("love/hearts/005-kiss-mark.png"), defaultWidth: 120, defaultHeight: 94 },
    ],
  },
  {
    id: "date",
    name: "데이트",
    stickers: [
      { id: "love.date.couple-rings", name: "반지", kind: "image", src: image("love/date/006-couple-rings.png"), defaultWidth: 120, defaultHeight: 84 },
      { id: "love.date.chocolate", name: "초콜릿", kind: "image", src: image("love/date/007-chocolate.png"), defaultWidth: 120, defaultHeight: 110 },
      { id: "love.date.icecream-share", name: "아이스크림", kind: "image", src: image("love/date/008-icecream-share.png"), defaultWidth: 77, defaultHeight: 120 },
      { id: "love.date.movie-popcorn", name: "팝콘", kind: "image", src: image("love/date/009-movie-popcorn.png"), defaultWidth: 100, defaultHeight: 120 },
      { id: "love.date.couple-key", name: "열쇠", kind: "image", src: image("love/date/010-couple-key.png"), defaultWidth: 62, defaultHeight: 120 },
    ],
  },
];

// 10 stickers
