/* Auto-generated by scripts/process-photowall-stickers.mjs — do not edit by hand. */
import type { StickerCategory } from "./types";

function image(path: string): string {
  return `/stickers/${path}`;
}

export const NIGHT_CATEGORIES: StickerCategory[] = [
  {
    id: "sky",
    name: "하늘",
    stickers: [
      { id: "night.sky.crescent", name: "초승달", kind: "image", src: image("night/sky/001-crescent.png"), defaultWidth: 112, defaultHeight: 120 },
      { id: "night.sky.stars", name: "별무리", kind: "image", src: image("night/sky/002-stars.png"), defaultWidth: 120, defaultHeight: 116 },
      { id: "night.sky.shooting-star", name: "유성", kind: "image", src: image("night/sky/003-shooting-star.png"), defaultWidth: 120, defaultHeight: 70 },
      { id: "night.sky.sleepy-cloud", name: "잠구름", kind: "image", src: image("night/sky/004-sleepy-cloud.png"), defaultWidth: 120, defaultHeight: 107 },
      { id: "night.sky.planet", name: "행성", kind: "image", src: image("night/sky/005-planet.png"), defaultWidth: 120, defaultHeight: 85 },
    ],
  },
  {
    id: "city",
    name: "도시",
    stickers: [
      { id: "night.city.streetlamp", name: "가로등", kind: "image", src: image("night/city/006-streetlamp.png"), defaultWidth: 54, defaultHeight: 120 },
      { id: "night.city.neon-sign", name: "네온", kind: "image", src: image("night/city/007-neon-sign.png"), defaultWidth: 120, defaultHeight: 115 },
      { id: "night.city.taxi", name: "택시", kind: "image", src: image("night/city/008-taxi.png"), defaultWidth: 120, defaultHeight: 66 },
      { id: "night.city.cocktail", name: "칵테일", kind: "image", src: image("night/city/009-cocktail.png"), defaultWidth: 98, defaultHeight: 120 },
      { id: "night.city.vinyl-night", name: "LP", kind: "image", src: image("night/city/010-vinyl-night.png"), defaultWidth: 120, defaultHeight: 119 },
    ],
  },
];

// 10 stickers
