/* Auto-generated by scripts/process-photowall-stickers.mjs — do not edit by hand. */
import type { StickerCategory } from "./types";

function image(path: string): string {
  return `/stickers/${path}`;
}

export const PARTY_CATEGORIES: StickerCategory[] = [
  {
    id: "celeb",
    name: "축하",
    stickers: [
      { id: "party.celeb.cake", name: "케이크", kind: "image", src: image("party/celeb/001-cake.png"), defaultWidth: 109, defaultHeight: 120 },
      { id: "party.celeb.balloon", name: "풍선", kind: "image", src: image("party/celeb/002-balloon.png"), defaultWidth: 87, defaultHeight: 120 },
      { id: "party.celeb.confetti", name: "컨페티", kind: "image", src: image("party/celeb/003-confetti.png"), defaultWidth: 120, defaultHeight: 115 },
      { id: "party.celeb.gift", name: "선물", kind: "image", src: image("party/celeb/004-gift.png"), defaultWidth: 115, defaultHeight: 120 },
      { id: "party.celeb.party-hat", name: "파티모자", kind: "image", src: image("party/celeb/005-party-hat.png"), defaultWidth: 81, defaultHeight: 120 },
    ],
  },
  {
    id: "fun",
    name: "재미",
    stickers: [
      { id: "party.fun.cheers", name: "건배", kind: "image", src: image("party/fun/006-cheers.png"), defaultWidth: 104, defaultHeight: 120 },
      { id: "party.fun.disco", name: "디스코", kind: "image", src: image("party/fun/007-disco.png"), defaultWidth: 113, defaultHeight: 120 },
      { id: "party.fun.camera-flash", name: "플래시", kind: "image", src: image("party/fun/008-camera-flash.png"), defaultWidth: 109, defaultHeight: 120 },
      { id: "party.fun.ticket", name: "티켓", kind: "image", src: image("party/fun/009-ticket.png"), defaultWidth: 120, defaultHeight: 86 },
      { id: "party.fun.crown", name: "왕관", kind: "image", src: image("party/fun/010-crown.png"), defaultWidth: 120, defaultHeight: 98 },
    ],
  },
];

// 10 stickers
