/* Auto-generated by scripts/process-photowall-stickers.mjs — do not edit by hand. */
import type { StickerCategory } from "./types";

function image(path: string): string {
  return `/stickers/${path}`;
}

export const SPRING_CATEGORIES: StickerCategory[] = [
  {
    id: "bloom",
    name: "꽃",
    stickers: [
      { id: "spring.bloom.sakura", name: "벚꽃", kind: "image", src: image("spring/bloom/001-sakura.png"), defaultWidth: 120, defaultHeight: 115 },
      { id: "spring.bloom.tulip", name: "튤립", kind: "image", src: image("spring/bloom/002-tulip.png"), defaultWidth: 69, defaultHeight: 120 },
      { id: "spring.bloom.butterfly", name: "나비", kind: "image", src: image("spring/bloom/003-butterfly.png"), defaultWidth: 120, defaultHeight: 107 },
      { id: "spring.bloom.bee", name: "벌", kind: "image", src: image("spring/bloom/004-bee.png"), defaultWidth: 116, defaultHeight: 120 },
      { id: "spring.bloom.dandelion", name: "민들레", kind: "image", src: image("spring/bloom/005-dandelion.png"), defaultWidth: 98, defaultHeight: 120 },
    ],
  },
  {
    id: "picnic",
    name: "피크닉",
    stickers: [
      { id: "spring.picnic.picnic-basket", name: "피크닉", kind: "image", src: image("spring/picnic/006-picnic-basket.png"), defaultWidth: 112, defaultHeight: 120 },
      { id: "spring.picnic.strawberry", name: "딸기", kind: "image", src: image("spring/picnic/007-strawberry.png"), defaultWidth: 101, defaultHeight: 120 },
      { id: "spring.picnic.lemonade", name: "레모네이드", kind: "image", src: image("spring/picnic/008-lemonade.png"), defaultWidth: 90, defaultHeight: 120 },
      { id: "spring.picnic.kite", name: "연", kind: "image", src: image("spring/picnic/009-kite.png"), defaultWidth: 70, defaultHeight: 120 },
      { id: "spring.picnic.bunny", name: "토끼", kind: "image", src: image("spring/picnic/010-bunny.png"), defaultWidth: 78, defaultHeight: 120 },
    ],
  },
];

// 10 stickers
