/* Auto-generated by scripts/process-photowall-stickers.mjs — do not edit by hand. */
import type { StickerCategory } from "./types";

function image(path: string): string {
  return `/stickers/${path}`;
}

export const SUMMER_CATEGORIES: StickerCategory[] = [
  {
    id: "beach",
    name: "비치",
    stickers: [
      { id: "summer.beach.volleyball", name: "비치발리볼", kind: "image", src: image("summer/beach/001-volleyball.png"), defaultWidth: 120, defaultHeight: 100 },
      { id: "summer.beach.volley-action", name: "스파이크", kind: "image", src: image("summer/beach/002-volley-action.png"), defaultWidth: 91, defaultHeight: 120 },
      { id: "summer.beach.beach-net", name: "비치 네트", kind: "image", src: image("summer/beach/003-beach-net.png"), defaultWidth: 120, defaultHeight: 97 },
      { id: "summer.beach.palm-tree", name: "야자수", kind: "image", src: image("summer/beach/004-palm-tree.png"), defaultWidth: 102, defaultHeight: 120 },
      { id: "summer.beach.umbrella", name: "파라솔", kind: "image", src: image("summer/beach/005-umbrella.png"), defaultWidth: 120, defaultHeight: 114 },
      { id: "summer.beach.sunglasses", name: "선글라스", kind: "image", src: image("summer/beach/006-sunglasses.png"), defaultWidth: 120, defaultHeight: 53 },
      { id: "summer.beach.flip-flops", name: "쪼리", kind: "image", src: image("summer/beach/007-flip-flops.png"), defaultWidth: 107, defaultHeight: 120 },
      { id: "summer.beach.surfboard", name: "서프보드", kind: "image", src: image("summer/beach/011-surfboard.png"), defaultWidth: 49, defaultHeight: 120 },
      { id: "summer.beach.flamingo", name: "플라밍고", kind: "image", src: image("summer/beach/012-flamingo.png"), defaultWidth: 117, defaultHeight: 120 },
      { id: "summer.beach.wave", name: "파도", kind: "image", src: image("summer/beach/013-wave.png"), defaultWidth: 120, defaultHeight: 113 },
      { id: "summer.beach.sun", name: "태양", kind: "image", src: image("summer/beach/014-sun.png"), defaultWidth: 118, defaultHeight: 120 },
      { id: "summer.beach.sandcastle", name: "모래성", kind: "image", src: image("summer/beach/016-sandcastle.png"), defaultWidth: 120, defaultHeight: 115 },
    ],
  },
  {
    id: "treats",
    name: "간식",
    stickers: [
      { id: "summer.treats.watermelon", name: "수박", kind: "image", src: image("summer/treats/008-watermelon.png"), defaultWidth: 120, defaultHeight: 106 },
      { id: "summer.treats.ice-cream", name: "아이스크림", kind: "image", src: image("summer/treats/009-ice-cream.png"), defaultWidth: 63, defaultHeight: 120 },
      { id: "summer.treats.coconut", name: "코코넛", kind: "image", src: image("summer/treats/010-coconut.png"), defaultWidth: 108, defaultHeight: 120 },
      { id: "summer.treats.lemonade", name: "레모네이드", kind: "image", src: image("summer/treats/015-lemonade.png"), defaultWidth: 92, defaultHeight: 120 },
    ],
  },
];

// 16 stickers
