/* Auto-generated by scripts/process-photowall-stickers.mjs — do not edit by hand. */
import type { StickerCategory } from "./types";

function image(path: string): string {
  return `/stickers/${path}`;
}

export const TRAVEL_CATEGORIES: StickerCategory[] = [
  {
    id: "trip",
    name: "여행",
    stickers: [
      { id: "travel.trip.airplane", name: "비행기", kind: "image", src: image("travel/trip/001-airplane.png"), defaultWidth: 120, defaultHeight: 70 },
      { id: "travel.trip.passport", name: "여권", kind: "image", src: image("travel/trip/002-passport.png"), defaultWidth: 105, defaultHeight: 120 },
      { id: "travel.trip.suitcase", name: "캐리어", kind: "image", src: image("travel/trip/003-suitcase.png"), defaultWidth: 75, defaultHeight: 120 },
      { id: "travel.trip.camera-travel", name: "카메라", kind: "image", src: image("travel/trip/004-camera-travel.png"), defaultWidth: 120, defaultHeight: 83 },
      { id: "travel.trip.map-pin", name: "핀", kind: "image", src: image("travel/trip/005-map-pin.png"), defaultWidth: 89, defaultHeight: 120 },
    ],
  },
  {
    id: "spot",
    name: "명소",
    stickers: [
      { id: "travel.spot.ticket-plane", name: "항공권", kind: "image", src: image("travel/spot/006-ticket-plane.png"), defaultWidth: 120, defaultHeight: 75 },
      { id: "travel.spot.landmark-tower", name: "타워", kind: "image", src: image("travel/spot/007-landmark-tower.png"), defaultWidth: 70, defaultHeight: 120 },
      { id: "travel.spot.compass", name: "나침반", kind: "image", src: image("travel/spot/008-compass.png"), defaultWidth: 103, defaultHeight: 120 },
      { id: "travel.spot.globe", name: "지구본", kind: "image", src: image("travel/spot/009-globe.png"), defaultWidth: 92, defaultHeight: 120 },
      { id: "travel.spot.stamp", name: "스탬프", kind: "image", src: image("travel/spot/010-stamp.png"), defaultWidth: 120, defaultHeight: 116 },
    ],
  },
];

// 10 stickers
