/* Auto-generated by scripts/process-photowall-stickers.mjs — do not edit by hand. */
import type { StickerCategory } from "./types";

function image(path: string): string {
  return `/stickers/${path}`;
}

export const WINTER_CATEGORIES: StickerCategory[] = [
  {
    id: "snow",
    name: "눈",
    stickers: [
      { id: "winter.snow.snowflake", name: "눈꽃", kind: "image", src: image("winter/snow/001-snowflake.png"), defaultWidth: 104, defaultHeight: 120 },
      { id: "winter.snow.snowman", name: "눈사람", kind: "image", src: image("winter/snow/002-snowman.png"), defaultWidth: 107, defaultHeight: 120 },
      { id: "winter.snow.penguin", name: "펭귄", kind: "image", src: image("winter/snow/003-penguin.png"), defaultWidth: 112, defaultHeight: 120 },
      { id: "winter.snow.mitten", name: "장갑", kind: "image", src: image("winter/snow/004-mitten.png"), defaultWidth: 89, defaultHeight: 120 },
      { id: "winter.snow.icicle", name: "고드름", kind: "image", src: image("winter/snow/005-icicle.png"), defaultWidth: 50, defaultHeight: 120 },
    ],
  },
  {
    id: "warm",
    name: "따뜻",
    stickers: [
      { id: "winter.warm.cocoa", name: "코코아", kind: "image", src: image("winter/warm/006-cocoa.png"), defaultWidth: 120, defaultHeight: 112 },
      { id: "winter.warm.earmuffs", name: "귀마개", kind: "image", src: image("winter/warm/007-earmuffs.png"), defaultWidth: 120, defaultHeight: 114 },
      { id: "winter.warm.beanie", name: "비니", kind: "image", src: image("winter/warm/008-beanie.png"), defaultWidth: 106, defaultHeight: 120 },
      { id: "winter.warm.fireplace", name: "벽난로", kind: "image", src: image("winter/warm/009-fireplace.png"), defaultWidth: 104, defaultHeight: 120 },
      { id: "winter.warm.gingerbread", name: "진저브레드", kind: "image", src: image("winter/warm/010-gingerbread.png"), defaultWidth: 98, defaultHeight: 120 },
    ],
  },
];

// 10 stickers
